services:
  # Backend Web Service
  - type: web
    name: eau-de-ceci-api
    env: docker
    region: oregon
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 8000
      - key: DEBUG
        value: false
      - key: APP_NAME
        value: Eau de Ceci API
      - key: CORS_ORIGINS
        value: '["*"]'
